/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        tertiary: '#005a3d',
        'inverse-on-surface': '#f3f0f4',
        background: '#fbf8fc',
        'on-tertiary-fixed-variant': '#005137',
        'on-background': '#1b1b1e',
        'surface-container-low': '#f6f2f7',
        'surface-container-lowest': '#ffffff',
        secondary: '#0051d5',
        'on-tertiary': '#ffffff',
        'surface-dim': '#dcd9dd',
        primary: '#630ed4',
        'surface-tint': '#732ee4',
        'outline-variant': '#ccc3d8',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#003ea8',
        'tertiary-fixed-dim': '#68dba9',
        'primary-fixed-dim': '#d2bbff',
        'error-container': '#ffdad6',
        'on-surface-variant': '#4a4455',
        'inverse-primary': '#d2bbff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e1e6',
        'secondary-container': '#316bf3',
        'on-tertiary-fixed': '#002114',
        'on-secondary-container': '#fefcff',
        surface: '#fbf8fc',
        'surface-variant': '#e4e1e6',
        'on-secondary-fixed': '#00174b',
        'surface-bright': '#fbf8fc',
        'primary-fixed': '#eaddff',
        'primary-container': '#7c3aed',
        'on-primary-fixed': '#25005a',
        'surface-container': '#f0edf1',
        'on-error-container': '#93000a',
        'on-primary-container': '#ede0ff',
        'tertiary-fixed': '#85f8c4',
        'on-secondary': '#ffffff',
        'inverse-surface': '#303033',
        'on-surface': '#1b1b1e',
        'on-primary-fixed-variant': '#5a00c6',
        'on-tertiary-container': '#88fbc6',
        'tertiary-container': '#007551',
        'on-error': '#ffffff',
        'surface-container-high': '#eae7eb',
        outline: '#7b7487',
        'secondary-fixed': '#dbe1ff',

        // Brand accent colors
        'violet': '#7C3AED',
        'blue': '#2563EB',
        'emerald': '#059669',
        'indigo': '#4F46E5',
        'cyan': '#06B6D4',
        'neutral-950': '#09090B',
        'neutral-900': '#18181B',
        'neutral-600': '#52525B',
        'neutral-400': '#A1A1AA',
        'border-hairline': '#E4E4E7',
        'border-hover': '#D4D4D8',
        'slate-900': '#0F172A',
        'slate-500': '#64748B',
        'terminal-green': '#A7F3D0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-4xl': '6rem',
        'container-max': '72rem',
        'space-xs': '0.25rem',
        'space-2xs': '0.125rem',
        'space-base': '1rem',
        'space-md': '0.75rem',
        'space-sm': '0.5rem',
        'gutter-desktop': '1.5rem',
        'space-3xl': '4rem',
        'space-xl': '2rem',
        'gutter-mobile': '1rem',
        'space-2xl': '3rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'headline-xl-mobile': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
        'label-sm': ['Geist'],
        'headline-lg': ['Space Grotesk'],
        'headline-2xl': ['Space Grotesk'],
        'body-sm': ['Geist'],
        'headline-2xl-mobile': ['Space Grotesk'],
        'body-lg': ['Geist'],
        'headline-xl': ['Space Grotesk'],
        'code-sm': ['Geist'],
        'label-md': ['Geist'],
        'body-md': ['Geist'],
        'headline-md': ['Space Grotesk'],
      },
      fontSize: {
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-2xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-2xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
